services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - ai-networks
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      - MODEL_NAME=llama3.2:1b
    networks:
      - ai-networks
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - ai-networks
    depends_on:
      fastapi-app:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    

volumes:
  ollama-models:
networks:
  ai-networks:
    driver: bridge
